runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api_gateway:app

service: default

env_variables:
  GOOGLE_CLOUD_PROJECT: "profsnotes"
  SECRET_VERSION: "latest"
  SECRET_ID: "openai-api-key"
  PINECONE_SECRET_ID: "pinecone-api-key"
  FIREBASE_ID: "firebase-admin-sdk-key"
    
instance_class: F2

automatic_scaling:
  min_idle_instances: 1
  max_instances: 20

handlers:
- url: /static
  static_dir: static
  http_headers:
    Cache-Control: "no-cache, no-store, max-age=0, must-revalidate"

- url: /
  static_files: static/index.html
  upload: static/index.html
  http_headers:
    Cache-Control: "no-cache, no-store, max-age=0, must-revalidate"

- url: /.*
  script: auto

service_account: profsnotes@appspot.gserviceaccount.com
